//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFIEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public long AccountTranID { get; set; }
        public long AccountMasterID { get; set; }
        public int AHID { get; set; }
        public Nullable<decimal> CrAmount { get; set; }
        public Nullable<decimal> DrAmount { get; set; }
        public bool IsActive { get; set; }
        public string Narration { get; set; }
        public Nullable<int> IsTranscation { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsMaster { get; set; }
    
        public virtual AccountMaster AccountMaster { get; set; }
        public virtual AccountHead AccountHead { get; set; }
    }
}
