//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFIEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountHead
    {
        public AccountHead()
        {
            this.AccountHead1 = new HashSet<AccountHead>();
            this.AccountMasters = new HashSet<AccountMaster>();
            this.AccountMasters1 = new HashSet<AccountMaster>();
            this.AccountTransactions = new HashSet<AccountTransaction>();
            this.ReceiptAppropriationPriorities = new HashSet<ReceiptAppropriationPriority>();
        }
    
        public int AHID { get; set; }
        public string AHCode { get; set; }
        public string AHName { get; set; }
        public string TE_AHName { get; set; }
        public int AHType { get; set; }
        public Nullable<int> ParentAHID { get; set; }
        public bool IsMemberTransaction { get; set; }
        public bool IsSLAccount { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public string OpeningBalanceType { get; set; }
        public int AHLevel { get; set; }
        public bool IsFederation { get; set; }
        public int StatusID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsSeed { get; set; }
        public string ORIGIN { get; set; }
        public Nullable<int> ORIGIN_OBJECT_ID { get; set; }
        public string DevComments { get; set; }
    
        public virtual ICollection<AccountHead> AccountHead1 { get; set; }
        public virtual AccountHead AccountHead2 { get; set; }
        public virtual RefValueMaster RefValueMaster { get; set; }
        public virtual ICollection<AccountMaster> AccountMasters { get; set; }
        public virtual ICollection<AccountMaster> AccountMasters1 { get; set; }
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
        public virtual ICollection<ReceiptAppropriationPriority> ReceiptAppropriationPriorities { get; set; }
    }
}
