//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFIEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptAppropriationPriority
    {
        public int RAPID { get; set; }
        public int AHID { get; set; }
        public byte Priority { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<System.DateTime> EffectiveFrom { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual AccountHead AccountHead { get; set; }
    }
}
