//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFIEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefValueMaster
    {
        public RefValueMaster()
        {
            this.AccountMasters = new HashSet<AccountMaster>();
            this.AccountHeads = new HashSet<AccountHead>();
        }
    
        public int RefID { get; set; }
        public int RefMasterID { get; set; }
        public string RefCode { get; set; }
        public string RefValue { get; set; }
        public string Description { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
        public bool IsSeedValue { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ICollection<AccountMaster> AccountMasters { get; set; }
        public virtual RefMaster RefMaster { get; set; }
        public virtual ICollection<AccountHead> AccountHeads { get; set; }
    }
}
